package callback;

import com.oracle.xmlns.adf.svc.types.ObjAttrHints;
import com.oracle.xmlns.adf.svc.types.ServiceViewInfo;
import com.oracle.xmlns.oracleas.schema.oracle_fault_11_0.FaultType;

import com.sun.xml.ws.api.addressing.AddressingVersion;
import com.sun.xml.ws.api.message.Header;
import com.sun.xml.ws.api.message.HeaderList;
import com.sun.xml.ws.developer.JAXWSProperties;

import javax.annotation.Resource;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.WebServiceContext;
import javax.xml.ws.soap.Addressing;

import sdo.commonj.java.ObjectFactory;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(targetNamespace="http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/",
  name="HCMDataLoaderResponse")
@XmlSeeAlso(
  { ObjectFactory.class, com.oracle.xmlns.oracleas.schema.oracle_fault_11_0.ObjectFactory.class, com.oracle.xmlns.adf.svc.types.ObjectFactory.class, sdo.commonj.ObjectFactory.class, com.oracle.xmlns.apps.hcm.common.dataloader.core.dataloaderintegrationservice.types.ObjectFactory.class, sdo.commonj.xml.ObjectFactory.class, com.oracle.xmlns.adf.svc.errors.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT)
@Addressing(enabled=true, required=true)
public class HCMDataLoaderResponseImpl
{
  @Resource
  private WebServiceContext wsContext;

  private static final AddressingVersion WS_ADDR_VER = AddressingVersion.W3C;

  @WebMethod(action="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0/Fault")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0/Fault")
  @Oneway
  public void onFault(@WebParam(targetNamespace="http://xmlns.oracle.com/oracleas/schema/oracle-fault-11_0",
      partName="parameters", name="Fault")
    FaultType parameters)
  {
    // Use the sample code to extract the relatesTo id for correlation and then add your rest of the logic

    System.out.println("Received the asynchronous reply");

    // get the messageId to correlate this reply with the original request
    HeaderList headerList = (HeaderList)wsContext.getMessageContext().get(JAXWSProperties.INBOUND_HEADER_LIST_PROPERTY);
    Header realtesToheader = headerList.get(WS_ADDR_VER.relatesToTag, true);
    String relatesToMessageId = realtesToheader.getStringContent();
    System.out.println("RelatesTo message id: " + relatesToMessageId);

    System.out.println("parameters: '" + parameters + "'");
    // Add your implementation here.
  }

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/importAndLoadDataAsyncResponse")
  @Action(input="http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/importAndLoadDataAsyncResponse")
  @RequestWrapper(localName="importAndLoadDataAsyncResponse",
    targetNamespace="http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/",
    className="com.oracle.xmlns.apps.hcm.common.dataloader.core.dataloaderintegrationservice.types.ImportAndLoadDataAsyncResponse")
  @Oneway
  public void importAndLoadDataAsyncResponse(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/",
      name="result")
    String result)
  {
    // Use the sample code to extract the relatesTo id for correlation and then add your rest of the logic

    System.out.println("Received the asynchronous reply");

    // get the messageId to correlate this reply with the original request
    HeaderList headerList = (HeaderList)wsContext.getMessageContext().get(JAXWSProperties.INBOUND_HEADER_LIST_PROPERTY);
    Header realtesToheader = headerList.get(WS_ADDR_VER.relatesToTag, true);
    String relatesToMessageId = realtesToheader.getStringContent();
    System.out.println("RelatesTo message id: " + relatesToMessageId);

    System.out.println("result: '" + result + "'");
    // Add your implementation here.
  }

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/getEntityListAsyncResponse")
  @Action(input="http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/getEntityListAsyncResponse")
  @RequestWrapper(localName="getEntityListAsyncResponse", targetNamespace="http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/",
    className="com.oracle.xmlns.apps.hcm.common.dataloader.core.dataloaderintegrationservice.types.GetEntityListAsyncResponse")
  @Oneway
  public void getEntityListAsyncResponse(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/",
      name="result")
    java.util.List<ServiceViewInfo> result)
  {
    // Use the sample code to extract the relatesTo id for correlation and then add your rest of the logic

    System.out.println("Received the asynchronous reply");

    // get the messageId to correlate this reply with the original request
    HeaderList headerList = (HeaderList)wsContext.getMessageContext().get(JAXWSProperties.INBOUND_HEADER_LIST_PROPERTY);
    Header realtesToheader = headerList.get(WS_ADDR_VER.relatesToTag, true);
    String relatesToMessageId = realtesToheader.getStringContent();
    System.out.println("RelatesTo message id: " + relatesToMessageId);

    System.out.println("result: '" + result + "'");
    // Add your implementation here.
  }

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/getDfltObjAttrHintsAsyncResponse")
  @Action(input="http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/getDfltObjAttrHintsAsyncResponse")
  @RequestWrapper(localName="getDfltObjAttrHintsAsyncResponse",
    targetNamespace="http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/",
    className="com.oracle.xmlns.apps.hcm.common.dataloader.core.dataloaderintegrationservice.types.GetDfltObjAttrHintsAsyncResponse")
  @Oneway
  public void getDfltObjAttrHintsAsyncResponse(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/",
      name="result")
    ObjAttrHints result)
  {
    // Use the sample code to extract the relatesTo id for correlation and then add your rest of the logic

    System.out.println("Received the asynchronous reply");

    // get the messageId to correlate this reply with the original request
    HeaderList headerList = (HeaderList)wsContext.getMessageContext().get(JAXWSProperties.INBOUND_HEADER_LIST_PROPERTY);
    Header realtesToheader = headerList.get(WS_ADDR_VER.relatesToTag, true);
    String relatesToMessageId = realtesToheader.getStringContent();
    System.out.println("RelatesTo message id: " + relatesToMessageId);

    System.out.println("result: '" + result + "'");
    // Add your implementation here.
  }

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/getServiceLastUpdateTimeAsyncResponse")
  @Action(input="http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/getServiceLastUpdateTimeAsyncResponse")
  @RequestWrapper(localName="getServiceLastUpdateTimeAsyncResponse",
    targetNamespace="http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/",
    className="com.oracle.xmlns.apps.hcm.common.dataloader.core.dataloaderintegrationservice.types.GetServiceLastUpdateTimeAsyncResponse")
  @Oneway
  public void getServiceLastUpdateTimeAsyncResponse(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/",
      name="result")
    XMLGregorianCalendar result)
  {
    // Use the sample code to extract the relatesTo id for correlation and then add your rest of the logic

    System.out.println("Received the asynchronous reply");

    // get the messageId to correlate this reply with the original request
    HeaderList headerList = (HeaderList)wsContext.getMessageContext().get(JAXWSProperties.INBOUND_HEADER_LIST_PROPERTY);
    Header realtesToheader = headerList.get(WS_ADDR_VER.relatesToTag, true);
    String relatesToMessageId = realtesToheader.getStringContent();
    System.out.println("RelatesTo message id: " + relatesToMessageId);

    System.out.println("result: '" + result + "'");
    // Add your implementation here.
  }

  @WebMethod(action="http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/getDataSetStatusAsyncResponse")
  @Action(input="http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/getDataSetStatusAsyncResponse")
  @RequestWrapper(localName="getDataSetStatusAsyncResponse",
    targetNamespace="http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/",
    className="com.oracle.xmlns.apps.hcm.common.dataloader.core.dataloaderintegrationservice.types.GetDataSetStatusAsyncResponse")
  @Oneway
  public void getDataSetStatusAsyncResponse(@WebParam(targetNamespace="http://xmlns.oracle.com/apps/hcm/common/dataLoader/core/dataLoaderIntegrationService/types/",
      name="result")
    String result)
  {
    // Use the sample code to extract the relatesTo id for correlation and then add your rest of the logic

    System.out.println("Received the asynchronous reply");

    // get the messageId to correlate this reply with the original request
    HeaderList headerList = (HeaderList)wsContext.getMessageContext().get(JAXWSProperties.INBOUND_HEADER_LIST_PROPERTY);
    Header realtesToheader = headerList.get(WS_ADDR_VER.relatesToTag, true);
    String relatesToMessageId = realtesToheader.getStringContent();
    System.out.println("RelatesTo message id: " + relatesToMessageId);

    System.out.println("result: '" + result + "'");
    // Add your implementation here.
  }
}
